#!/usr/bin/bash
#PBS -l nodes=1:ppn=5

# Here we are locating the directory with data.
cd /absolute/path/to/the/working/directory

# Here we are setting the background for conda environment activation.
eval "$(conda shell.bash hook)"

# # Here we are setting the background for conda environment activation. This will retrieve details of the packages installed on Miniconda.
conda activate bioinfo

# Here we are filtering biallelic variants as we only want variants that are covered on both copies of chromosomes.
bcftools view -Oz -m 2 -M 2 -q 0.01:minor nameoffile.calls.norm.flt-indels.vcf.gz -o nameoffile.calls.biallelic.vcf.gz --threads 5

# indexing the input file
bcftools index nameoffile.calls.biallelic.vcf.gz

done
